INSERT INTO users VALUES
                      ('395bff17-2b1d-42ad-972d-ab9c93646b85', 'jonathan', 'jonathan.bosker@students.uu.nl', 'Jonathan', 'Bosker', 'Daltonlaan 501', '3584BK', 'Utrecht', '$2b$10$2EXnCQ6svM4fipZ3fYVSvuZ2scrfFHewRzb6r7wxI2UeKEChA6ebC'),
                      ('6a230015-87c1-4944-b99e-dedfe9cdaf35', 'sergey', 's.sosnovsky@uu.nl', 'Sergey', 'Sosnovsky', 'Princetonplein 5', '3584CC', 'Utrecht', '$2b$10$h6gJYNLndMw4vXBycZfu1uarzoZ7RYN5tnkCiqJ39hN6phE9yJlcS'),
                      ('159ba078-9eab-4585-be96-6068414e2a0c', 'tijmen', 'tijmen.vis@students.uu.nl', 'Tijmen', 'Vis', 'Leuvenlaan 4', '3584CE', 'Utrecht', '$2b$10$QBUYgCb2RjzjJ98unqLzQeVHMuYYqOArk0JPrayNhAXeKAAqTJtDG'),
                      ('addaadbe-7098-4cc9-bbc0-2a7ad668c19b', 'pimp', 'pimp@yahoo.com', 'Donald', 'J. Trump', 'Verlengde Slotlaan 79', '3707CD', 'Zeist', '$2b$10$SBkbKDV3il.xUYmCccYM1ehP2T6wzvtaE9F6lbNqv4hooMqzkbS7e'),
                      ('15fe00ef-9300-4af2-9352-48bbb442e6ef', 'cerberus', 'vo@omhcerberus.nl', 'Mannen', 'v.d. Honden', 'Ramaekersweg 68', '3827GH', 'Maastricht', '$2b$10$8ynx67ecpBD0LDdSc0e6T.IVOa6S9joiV1QNXN3xw1RN70SDjSwVm');

INSERT INTO authors VALUES
                        (NULL, 'Joanne', 'Rowling', 'J. K. Rowling', 'https://en.wikipedia.org/wiki/J._K._Rowling'),
                        (NULL, 'Frank', 'Herbert', NULL, 'https://en.wikipedia.org/wiki/Frank_Herbert'),
                        (NULL, 'Jeffrey', 'Patrick Kinney', 'Jeff Kinney', 'https://en.wikipedia.org/wiki/Jeff_Kinney'),
                        (NULL, 'John', 'Ronald Reuel Tolkien', 'J. R. R. Tolkien', 'https://en.wikipedia.org/wiki/J._R._R._Tolkien'),
                        (NULL, 'Richard', 'Russell Riordan Jr.', 'Rick Riordan', 'https://en.wikipedia.org/wiki/Rick_Riordan'),
                        (NULL, 'Stephanie', 'Meyer', NULL, 'https://en.wikipedia.org/wiki/Stephenie_Meyer');

INSERT INTO books VALUES
                      (9780316228534, 1, 'The Casual Vacancy', 'https://upload.wikimedia.org/wikipedia/en/9/91/The_Casual_Vacancy.jpg', ''),
                      (9781338732870, 1, 'The Ickabog', 'https://upload.wikimedia.org/wikipedia/en/d/de/The_Ickabog_%28Rowling_book%29.jpeg', ''),
                      (9781444964912, 1, 'The Christmas Pig', 'https://upload.wikimedia.org/wikipedia/en/3/3b/The_Christmas_Pig_first_edition_cover.jpg', '')
                      (9780747532699, 1, 'Harry Potter and the Philosopher's Stone', 'https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg', 'Harry Potter and the Philosopher's Stone is a fantasy novel written by British author J. K. Rowling. The first novel in the Harry Potter series and Rowling's debut novel, it follows Harry Potter, a young wizard who discovers his magical heritage on his eleventh birthday, when he receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry. Harry makes close friends and a few enemies during his first year at the school and with the help of his friends, Ron Weasley and Hermione Granger, he faces an attempted comeback by the dark wizard Lord Voldemort, who killed Harry's parents, but failed to kill Harry when he was just 15 months old.'),
                      (0747538492, 1, 'Harry Potter and the Chamber of Secrets', 'https://upload.wikimedia.org/wikipedia/en/5/5c/Harry_Potter_and_the_Chamber_of_Secrets.jpg', 'Harry Potter and the Chamber of Secrets is a fantasy novel written by British author J. K. Rowling and the second novel in the Harry Potter series. The plot follows Harry's second year at Hogwarts School of Witchcraft and Wizardry, during which a series of messages on the walls of the school's corridors warn that the "Chamber of Secrets" has been opened and that the "heir of Slytherin" would kill all pupils who do not come from all-magical families. These threats are found after attacks that leave residents of the school petrified. Throughout the year, Harry and his friends Ron and Hermione investigate the attacks.'),
                      (0747542155, 1, 'Harry Potter and the Prisoner of Azkaban', 'https://upload.wikimedia.org/wikipedia/en/a/a0/Harry_Potter_and_the_Prisoner_of_Azkaban.jpg', 'Harry Potter and the Prisoner of Azkaban is a fantasy novel written by British author J. K. Rowling and is the third in the Harry Potter series. The book follows Harry Potter, a young wizard, in his third year at Hogwarts School of Witchcraft and Wizardry. Along with friends Ronald Weasley and Hermione Granger, Harry investigates Sirius Black, an escaped prisoner from Azkaban, the wizard prison, believed to be one of Lord Voldemort's old allies.'),
                      (9781551925158, 1, Harry Potter and the Goblet of Fire', 'https://upload.wikimedia.org/wikipedia/en/b/b6/Harry_Potter_and_the_Goblet_of_Fire_cover.png', 'Harry Potter and the Goblet of Fire is a fantasy novel written by British author J. K. Rowling and the fourth novel in the Harry Potter series. It follows Harry Potter, a wizard in his fourth year at Hogwarts School of Witchcraft and Wizardry, and the mystery surrounding the entry of Harry's name into the Triwizard Tournament, in which he is forced to compete.'),
                      (0747551006, 1, 'Harry Potter and the Order of the Phoenix', 'https://upload.wikimedia.org/wikipedia/en/7/70/Harry_Potter_and_the_Order_of_the_Phoenix.jpg', 'Harry Potter and the Order of the Phoenix is a fantasy novel written by British author J. K. Rowling and the fifth novel in the Harry Potter series. It follows Harry Potter's struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L. exams, and an obstructive Ministry of Magic. The novel was published on 21 June 2003 by Bloomsbury in the United Kingdom, Scholastic in the United States, and Raincoast in Canada. It sold five million copies in the first 24 hours of publication.'),
                      (0747581088, 1, 'Harry Potter and the Half-Blood Prince' ,'https://upload.wikimedia.org/wikipedia/en/b/b5/Harry_Potter_and_the_Half-Blood_Prince_cover.png', 'Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J. K. Rowling and the sixth and penultimate novel in the Harry Potter series. Set during Harry Potter's sixth year at Hogwarts, the novel explores the past of the boy wizard's nemesis, Lord Voldemort, and Harry's preparations for the final battle against Voldemort alongside his headmaster and mentor Albus Dumbledore.'),
                      (0747591059, 1, 'Harry Potter and the Deathly Hallows', ,'https://upload.wikimedia.org/wikipedia/en/a/a9/Harry_Potter_and_the_Deathly_Hallows.jpg', 'Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling and the seventh and final novel in the Harry Potter series. It was released on 21 July 2007 in the United Kingdom by Bloomsbury Publishing, in the United States by Scholastic, and in Canada by Raincoast Books. The novel chronicles the events directly following Harry Potter and the Half-Blood Prince (2005) and the final confrontation between the wizards Harry Potter and Lord Voldemort.'),
                      (9780441013593, 2, 'Dune', 'https://upload.wikimedia.org/wikipedia/en/d/de/Dune-Frank_Herbert_%281965%29_First_edition.jpg', 'Dune is a 1965 science fiction novel by American author Frank Herbert, originally published as two separate serials in Analog magazine. It is the first novel in the Dune series, and it established Herbert as a significant science fiction author.'),
                      (9780441172696, 2, 'Dune Messiah', 'https://upload.wikimedia.org/wikipedia/en/4/46/Dune_Messiah-Frank_Herbert_%281969%29_First_edition.jpg', 'Dune Messiah is a science fiction novel by American author Frank Herbert, published in 1969. It is the second novel in the Dune series, following the 1965 novel Dune.'),
                      (9780441104024, 2, 'Children of Dune', 'https://upload.wikimedia.org/wikipedia/en/f/f8/Children_of_Dune-Frank_Herbert_%281976%29_First_edition.jpg', 'Children of Dune is a science fiction novel by Frank Herbert, published in 1976. It is the third novel in the Dune series and takes place twelve years after the events of Dune Messiah.'),
                      (9780441294671, 2, 'God Emperor of Dune', 'https://upload.wikimedia.org/wikipedia/en/a/a7/God_Emperor_of_Dune-Frank_Herbert_%281981%29_First_edition.jpg', 'God Emperor of Dune is a science fiction novel by Frank Herbert, published in 1981. It is the fourth novel in the Dune series and is set thousands of years after the events of the previous novels.'),
                      (9780441328000, 2, 'Heretics of Dune', 'https://upload.wikimedia.org/wikipedia/en/d/de/Heretics_of_Dune-Frank_Herbert_%281984%29_First_edition.jpg', 'Heretics of Dune is a science fiction novel by Frank Herbert, published in 1984. It is the fifth novel in the Dune series and focuses on the struggle between different factions and organizations on the desert planet Arrakis.'),
                      (9780441102679, 2, 'Chapterhouse: Dune', 'https://upload.wikimedia.org/wikipedia/en/8/82/Chapterhouse_Dune-Frank_Herbert_%281985%29_First_edition.jpg', 'Chapterhouse: Dune is a science fiction novel by Frank Herbert, published in 1985. It is the sixth novel in the Dune series and continues the story of the Bene Gesserit sisterhood and their struggles on Arrakis.')              
                      (9780810993136, 3, 'Diary of a Wimpy Kid', 'https://upload.wikimedia.org/wikipedia/en/8/84/Diary_of_a_Wimpy_Kid_book_cover.jpg', 'Diary of a Wimpy Kid is a children's novel written and illustrated by Jeff Kinney. It is the first book in the Diary of a Wimpy Kid series. The book is about a boy named Greg Heffley and his attempts to become popular in his first year of middle school.'),
                      (9780810994737, 3, 'Diary of a Wimpy Kid: Rodrick Rules', 'https://upload.wikimedia.org/wikipedia/en/8/80/Diary_of_a_Wimpy_Kid_Rodrick_Rules_book_cover.png', 'Rodrick Rules is the second book in the Diary of a Wimpy Kid series. It continues Greg Heffley''s middle school experiences and his interactions with his older brother Rodrick.'),
                      (9780810970687, 3, 'Diary of a Wimpy Kid: The Last Straw', 'https://upload.wikimedia.org/wikipedia/en/0/04/Diary_of_a_Wimpy_Kid_The_Last_Straw_book_cover.png', 'The Last Straw is the third book in the series, depicting Greg''s challenges and adventures as he navigates the ups and downs of middle school life.'),
                      (9780810970915, 3, 'Diary of a Wimpy Kid: Dog Days', 'https://upload.wikimedia.org/wikipedia/en/7/78/Diary_of_a_Wimpy_Kid_Dog_Days_book_cover.jpg', 'Dog Days follows Greg Heffley''s summer experiences, including family vacations, friendship dilemmas, and the trials of growing up.'),
                      (9780141331973, 3, 'Diary of a Wimpy Kid: The Ugly Truth', 'https://upload.wikimedia.org/wikipedia/en/0/0a/Diary_of_a_Wimpy_Kid_The_Ugly_Truth_book_cover.jpg', 'The Ugly Truth is the fifth book in the series, focusing on Greg''s struggles with adolescence, friendships, and family dynamics.'),
                      (9781419702235, 3, 'Diary of a Wimpy Kid: Cabin Fever', 'https://upload.wikimedia.org/wikipedia/en/f/f5/Diary_of_a_Wimpy_Kid_Cabin_Fever_book_cover.jpg', 'Cabin Fever is another humorous installment in the series, exploring Greg''s winter escapades and the chaos that ensues during the holiday season.'),
                      (9781419705847, 3, 'Diary of a Wimpy Kid: The Third Wheel', 'https://upload.wikimedia.org/wikipedia/en/8/86/Diary_of_a_Wimpy_Kid_The_Third_Wheel_book_cover.jpg', 'The Third Wheel is the seventh book in the series, focusing on Greg''s attempts to find a date for the Valentine''s Day dance while navigating middle school friendships and challenges.'),
                      (9781419711329, 3, 'Diary of a Wimpy Kid: Hard Luck', 'https://upload.wikimedia.org/wikipedia/en/6/61/Diary_of_a_Wimpy_Kid_Hard_Luck_book_cover.jpg', 'Hard Luck is the eighth book in the series, where Greg faces various obstacles and setbacks as he tries to change his fortunes and find his lucky break.'),
                      (9781419711893, 3, 'Diary of a Wimpy Kid: The Long Haul', 'https://upload.wikimedia.org/wikipedia/en/3/3c/Diary_of_a_Wimpy_Kid_The_Long_Haul_book_cover.jpg', 'The Long Haul is the ninth book in the series, following Greg and his family on a road trip filled with mishaps, humor, and unexpected adventures.'),
                      (9781419717017, 3, 'Diary of a Wimpy Kid: Old School', 'https://upload.wikimedia.org/wikipedia/en/8/87/Diary_of_a_Wimpy_Kid_Old_School_book_cover.jpg', 'Old School is the tenth book in the series, exploring Greg''s experiences when his middle school goes "old school" with no electronics, leading to hilarious situations and new challenges.'),
                      (9781419723445, 3, 'Diary of a Wimpy Kid: Double Down', 'https://upload.wikimedia.org/wikipedia/en/c/c8/Diary_of_a_Wimpy_Kid_Double_Down_book_cover.jpg', 'Double Down is the eleventh book in the series, where Greg decides to pursue a new hobby—making a scary movie—leading to comedic misadventures and unexpected outcomes.'),
                      (9781419725456, 3, 'Diary of a Wimpy Kid: The Getaway', 'https://upload.wikimedia.org/wikipedia/en/3/33/Diary_of_a_Wimpy_Kid_The_Getaway_book_cover.jpg', 'The Getaway is the twelfth book in the series, as Greg and his family go on a tropical vacation filled with sun, sand, and surprises, making it a holiday to remember.'),
                      (9781419727436, 3, 'Diary of a Wimpy Kid: The Meltdown', 'https://upload.wikimedia.org/wikipedia/en/4/47/Diary_of_a_Wimpy_Kid_The_Meltdown_cover.png', 'The Meltdown is the thirteenth book in the series, set in the midst of a winter storm that turns Greg''s neighborhood into a battleground for snowball fights and warring factions.'),
                      (9781419739033, 3, 'Diary of a Wimpy Kid: Wrecking Ball', 'https://upload.wikimedia.org/wikipedia/en/1/15/Diary_of_a_Wimpy_Kid_Wrecking_Ball_cover.jpg', 'Wrecking Ball is the fourteenth book in the series, where Greg discovers unexpected family secrets during a home renovation project that spirals out of control.'),
                      (9781419748684, 3, 'Diary of a Wimpy Kid: The Deep End', 'https://upload.wikimedia.org/wikipedia/en/7/79/Diary_of_a_Wimpy_Kid_The_Deep_End_cover.png', 'The Deep End is the fifteenth book in the series, as Greg and his family embark on a camping trip that quickly turns into a hilarious and chaotic adventure.'),
                      (9781419749155, 3, 'Diary of a Wimpy Kid: Big Shot', 'https://upload.wikimedia.org/wikipedia/en/e/e2/Diary_of_a_Wimpy_Kid%2C_The_Big_Shot.jpg', 'In Big Shot, book 16 of the Diary of a Wimpy Kid series from #1 international bestselling author Jeff Kinney, Greg Heffley and sports just don’t mix.'),
                      (9781419762949, 3, 'Diary of a Wimpy Kid: Diper Överlöde', 'https://upload.wikimedia.org/wikipedia/en/4/47/Diary_of_a_Wimpy_Kid%2C_Diper_%C3%96verl%C3%B6de_%28Jeff_Kinney%29.png', 'In Diper Överlöde, book 17 of the Diary of a Wimpy Kid series from #1 international bestselling author Jeff Kinney, Greg Heffley is finding out that the road to fame and glory comes with some hard knocks.'),
                      (9781419766947, 3, 'Diary of a Wimpy Kid: No Brainer', 'https://upload.wikimedia.org/wikipedia/en/7/76/DOAWK_No_Brainer_cover_art.png', 'In No Brainer, book 18 of the Diary of a Wimpy Kid series from #1 international bestselling author Jeff Kinney, it’s up to Greg to save his crumbling school before it’s shuttered for good.'),
                      (9781419766954, 3, 'Diary of a Wimpy Kid: Hot Mess', 'https://static.wikia.nocookie.net/doawk/images/2/27/Diary_of_a_Wimpy_Kid-_Hot_Mess_Cover.jpg/revision/latest?cb=20240325052014', 'International bestselling author Jeff Kinney serves up heaps of laughs in Hot Mess, the 19th book in the Diary of a Wimpy Kid series. Greg Heffley is caught in the middle as the two halves of his extended family come together in a sidesplittingly relatable summer story!'),
                      (9780618640157, 4, 'The Fellowship of the Ring', 'https://upload.wikimedia.org/wikipedia/en/8/8e/The_Fellowship_of_the_Ring_cover.gif', 'The Fellowship of the Ring is the first book in J.R.R. Tolkien''s epic fantasy trilogy "The Lord of the Rings," following the journey of the Ring-bearer Frodo Baggins and the formation of the Fellowship.'),
                      (9780358652984, 4, 'The Two Towers', 'https://upload.wikimedia.org/wikipedia/en/a/a1/The_Two_Towers_cover.gif', 'The Two Towers is the second book in the series, continuing the adventures of Frodo and the Fellowship as they face challenges and threats from Sauron''s forces while seeking to destroy the One Ring.'),
                      (9780261102378, 4, 'The Return of the King', 'https://upload.wikimedia.org/wikipedia/en/1/11/The_Return_of_the_King_cover.gif', 'The Return of the King is the concluding book in the trilogy, depicting the final stages of the War of the Ring, the fate of Middle-earth, and the ultimate destiny of its characters.'),
                      (9780547928227, 4, 'The Hobbit', 'https://upload.wikimedia.org/wikipedia/en/4/4a/TheHobbit_FirstEdition.jpg', 'The Hobbit, or There and Back Again, is a prelude to "The Lord of the Rings" and follows the adventures of Bilbo Baggins, Gandalf, and a company of dwarves on a quest to reclaim treasure guarded by the dragon Smaug.');
                      (978004823139-0, 4, 'The Silmarillion', 'https://upload.wikimedia.org/wikipedia/en/d/db/Silmarillion.png', 'The Silmarillion is a collection of mythopoeic stories set in Tolkien''s fictional universe, exploring the creation of Middle-earth, the history of the Elves, the struggles against evil, and the legacies of heroes.'),
                      (9780618894642, 4, 'The Children of Húrin', 'https://upload.wikimedia.org/wikipedia/en/8/85/The_Children_of_Hurin_cover.jpg', 'The Children of Húrin is a standalone novel based on Tolkien''s posthumously published work, recounting the tragic tale of the cursed hero Túrin Turambar and his struggles against Morgoth.'),
                      (9780048231796, 4, 'The Unfinished Tales', 'https://upload.wikimedia.org/wikipedia/en/3/3d/UnfinishedTales.JPG', 'The Unfinished Tales is a collection of narratives and writings by Tolkien, providing additional insights into the history, cultures, and events of Middle-earth, including stories related to "The Hobbit" and "The Lord of the Rings."'),
                      (0786856297, 5, 'The Lightning Thief', 'https://upload.wikimedia.org/wikipedia/en/3/3b/The_Lightning_Thief_cover.jpg', 'The Lightning Thief is a 2005 American fantasy-adventure novel based on Greek mythology, the first young adult novel by Rick Riordan. The opening installment in the series Percy Jackson & the Olympians, the book was recognized among the year's best for young adults. Riordan followed the novel with various books and spin-off series, spawning the Camp Half-Blood Chronicles media franchise.'),
                      (0786856866, 5, 'The Sea of Monsters', 'https://upload.wikimedia.org/wikipedia/en/4/46/PercySeamonsters.gif', 'The Sea of Monsters is an American fantasy-adventure novel based on Greek mythology written by Rick Riordan and published in 2006. It is the second novel in the Percy Jackson & the Olympians series and the sequel to The Lightning Thief. This book chronicles the adventures of thirteen-year-old demigod Percy Jackson as he and his friends rescue his satyr friend Grover from the Cyclops Polyphemus and save Camp Half-Blood from a Titan's attack by bringing the Golden Fleece to cure Thalia's poisoned pine tree.'),
                      (9781423101451, 5, 'The Titan's Curse', 'https://upload.wikimedia.org/wikipedia/en/3/3c/The_titan%27s_curse.jpg', 'The Titan's Curse is an American fantasy-adventure novel based on Greek mythology written by Rick Riordan. It was released on May 1, 2007, and is the third novel in the Percy Jackson & the Olympians series and the sequel to The Sea of Monsters. It is about the adventures of the 14-year-old demigod Percy Jackson as he and his friends go on a dangerous quest to rescue his 14-year-old demigod friend Annabeth Chase and the Greek goddess Artemis, who have both been kidnapped by the titans.'),
                      (9781423101468, 5, 'The Battle of the Labyrinth', 'https://upload.wikimedia.org/wikipedia/en/b/bf/PercyBattleLabyrinth.jpg', 'The Battle of the Labyrinth is an American fantasy-adventure novel based on Greek mythology written by Rick Riordan. It is the fourth novel in the Percy Jackson & the Olympians series. The novel was first published in the United States on 6 May 2008 by Hyperion Books for Children, an imprint of Disney Publishing Worldwide. It has been published in hardcover, audiobook, ebook, and large-print editions.'),
                      (9781423101475, 5, 'The Last Olympian', 'https://upload.wikimedia.org/wikipedia/en/9/99/Lastolympian.gif', 'The Last Olympian is a fantasy-adventure novel based on Greek mythology by Rick Riordan, published on May 5, 2009. It is the fifth novel of the Percy Jackson & the Olympians series and serves as the direct sequel to The Battle of the Labyrinth. The Last Olympian revolves around the demigod Percy Jackson as he leads his friends in a last stand to protect Mount Olympus.'),
                      (9781368098175, 5, 'The Chalice of the Gods', https://upload.wikimedia.org/wikipedia/en/f/f1/The_Chalice_of_the_Gods.jpg, 'The Chalice of the Gods is a fantasy-adventure novel based on Greek mythology by Rick Riordan. It was released on September 26, 2023 by Disney Hyperion. It is the sixth novel of the Percy Jackson & the Olympians series, and serves as a follow-up to the original five books, taking place after the events of the series The Heroes of Olympus but before the series The Trials of Apollo.'),
                      (9780316015844, 6, 'Twilight', 'https://upload.wikimedia.org/wikipedia/en/1/1d/Twilightbook.jpg', 'Twilight is the first book in the "Twilight" series by Stephenie Meyer. It tells the story of Bella Swan, a teenage girl who falls in love with Edward Cullen, a vampire. The novel explores their romantic relationship amidst the challenges posed by vampire society and other supernatural forces.'),
                      (9780316160193, 6, 'New Moon', 'https://upload.wikimedia.org/wikipedia/en/8/89/Newmooncover.jpg', 'New Moon is the second book in the series, continuing the story of Bella and Edward as Bella faces challenges after Edward leaves her. She forms a close friendship with Jacob Black, uncovering the secrets of his werewolf heritage and the larger supernatural world.'),
                      (9780316160209, 6, 'Eclipse', 'https://upload.wikimedia.org/wikipedia/en/2/20/Eclipsecover.jpg', 'Eclipse is the third book, focusing on the love triangle between Bella, Edward, and Jacob as they confront new threats, including a group of rogue vampires. Bella must make difficult choices about her future and her relationships with the two supernatural beings.'),
                      (9780316032148, 6, 'Breaking Dawn', 'https://upload.wikimedia.org/wikipedia/en/3/31/Breaking_Dawn_cover.jpg', 'Breaking Dawn is the final book in the series, depicting Bella and Edward''s marriage, Bella''s transformation into a vampire, and the challenges they face as they protect their family from various dangers, including the powerful Volturi vampire coven.'),
                      (9780316505451, 6, 'Life and Death: Twilight Reimagined', 'https://upload.wikimedia.org/wikipedia/en/6/65/TwilightReimaginedbook.jpg', 'Life and Death: Twilight Reimagined (2015) is a gender-swapped version of "Twilight," where Bella Swan becomes Beau Swan and Edward Cullen becomes Edythe Cullen. The novel explores a similar story with reversed gender roles and some differences in character dynamics.'),
                      (9780316707046, 6, 'Midnight Sun', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Midnight_Sun_-_Stephanie_Meyer_novel_cover_artwork.jpg', 'Midnight Sun (2020) is a companion novel to the "Twilight" series, narrated from Edward Cullen''s perspective. It revisits the events of "Twilight" but provides insights into Edward''s thoughts, feelings, and struggles as a vampire in love with a human.');

INSERT INTO reviews VALUES
                        ();

INSERT INTO reservations VALUES
                             ();
